/* RTQL8, Copyright (c) 2011, Georgia Tech Research Corporation
 * All rights reserved.
 *
 * Author(s): John Turner <jturner65@gatech.edu>
 * Georgia Tech Graphics Lab
 * 
 * This file is provided under the following "BSD-style" License:
 *   Redistribution and use in source and binary forms, with or
 *   without modification, are permitted provided that the following
 *   conditions are met:
 *   * Redistributions of source code must retain the above copyright
 *     notice, this list of conditions and the following disclaimer.
 *   * Redistributions in binary form must reproduce the above
 *     copyright notice, this list of conditions and the following
 *     disclaimer in the documentation and/or other materials provided
 *     with the distribution.
 *   * This code incorporates portions of Open Dynamics Engine 
 *     (Copyright (c) 2001-2004, Russell L. Smith. All rights 
 *     reserved.) and portions of FCL (Copyright (c) 2011, Willow 
 *     Garage, Inc. All rights reserved.), which were released under
 *     the same BSD license as below
 *
 *   THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND
 *   CONTRIBUTORS "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES,
 *   INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF
 *   MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
 *   DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR
 *   CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
 *   SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
 *   LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF
 *   USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED
 *   AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
 *   LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN
 *   ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 *   POSSIBILITY OF SUCH DAMAGE.
 */

#ifndef __KINUIPAGE_H__
#define __KINUIPAGE_H__

#include "KinHndlrConsts.h"
#include "KinUIComponent.h"
#include "KinUIButton.h"
#include "KinUISlider.h"
#include "KinUICrank.h"
#include "KinUIImageButton.h"
#include "KinUIPrgBar.h"
#include "KinUITimer.h"
#include "KinUICaption.h"
#include "KinUITextBox.h"

using namespace std;

namespace rtql8 {
    namespace kinect{ 
        class KinUIPage {
        public:
            std::string name;
            std::string onload;
            vector<std::shared_ptr<KinUIComponent> >    KinPgUICmp;          
            vector<std::shared_ptr<KinUIButton> >       KinPgUIBtn;
            vector<std::shared_ptr<KinUISlider> >       KinPgUISldr;
            vector<std::shared_ptr<KinUICrank> >		KinPgUICrnk;					
            vector<std::shared_ptr<KinUIImageButton> >	KinPgUIImgBtn;				
            vector<std::shared_ptr<KinUIPrgBar> >		KinPgUIProgBar;					
            vector<std::shared_ptr<KinUITimer> >		KinPgUITimer;		
            vector<std::shared_ptr<KinUICaption> >		KinPgUICaption;		
            vector<std::shared_ptr<KinUITextBox> >		KinPgUITextBox;							//holding kinect textboxes (modified buttons able to accept and process typed input)

            //UIpage should own the primary functionality here! TODO:
            //go through all elements and check to see if events have occured in them
            //d < 0 means event triggered by mouse
            //mouseEvent : if this is an event generated by the mouse or by the kinect
            //hand : which hand/button was cliked
            //evnt : the nature of the event : 0 : up, 1 : click/push, 2 : drag/grab
            bool checkUIElements(int& x, int& y, int& d, bool mouseEvent, int hand, int evnt);

            int numComponents() { return KinPgUICmp.size(); }
            void addUIButton(KinUIButton* btn);
            void addUISlider(KinUISlider* sld);
            void addUICrank(KinUICrank* crk);
            void addUIImgBtn(KinUIImageButton* ibtn);
            void addUIPrgBar(KinUIPrgBar* pbar);
            void addUITimer(KinUITimer* tmr);
            void addUITextBox(KinUITextBox* tbx);
            void addUICaption(KinUICaption* cap);
        };

    }//namespace kinect
}//namespace rtql8

#endif // #ifndef __KINUIPAGE_H__
