// This file is automatically generated from CMake
#ifndef UTILS_PATHS_H
#define UTILS_PATHS_H

#define RTQL8_ROOT_PATH "C:/dev/knowledge-rtql8/"
#define RTQL8_DATA_PATH "C:/dev/knowledge-rtql8/data/"
#define WRTQL8_DATA_PATH L"C:/dev/knowledge-rtql8/data/"

#endif // ifndef UTILS_PATHS_H
